apiVersion: apps/v1
kind: Deployment
metadata:
  name: framepack-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: framepack-worker
  template:
    metadata:
      labels:
        app: framepack-worker
    spec:
      containers:
      - name: framepack-worker
        image: sofarc6soat/framepack-worker:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10