version: '3.9'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    user: root
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-local-setup:
    container_name: dynamodb-local-setup
    image: amazon/aws-cli
    volumes:
      - "./tests/schemas:/tmp/dynamo"
    env_file:
      - ../kubernetes/.env

  framepack-worker:
    build:
      context: ../../src
      dockerfile: ./Worker/Dockerfile
    restart: always
    image: framepack-worker
    container_name: framepack-worker
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - framepack-worker-network

networks:
  framepack-worker-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.173.0.0/16
          gateway: 172.173.0.1