name: .NET Core Tests and Deployments

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set UTF-8 encoding
      - name: Set encoding to UTF-8
        run: |
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./Framepack-Worker.sln

      # Run unit tests with coverage
      - name: Run all tests with coverage
        run: |
          dotnet test Framepack-Worker.sln \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory tests/TestResults \
          --logger:"trx;LogFileName=TestResults.trx" \
          --diag:log-detailed.txt \
          -- RunConfiguration.DisableAppDomain=true

      # Display detailed logs if tests fail
      - name: Display test logs
        if: failure()
        run: cat log-detailed.txt | iconv -f utf-8 -t utf-8

  code_analysis:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v3

      # 2. Configuração do .NET SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Cache do SonarCloud
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 4. Cache do SonarCloud Scanner
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      # 5. Instalação do SonarCloud Scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "${DOTNET_ROOT}/tools" >> $GITHUB_PATH

      # 6. Instalação do dotnet-coverage
      - name: Install dotnet-coverage
        run: |
          dotnet tool install --global dotnet-coverage

      # 7. Configuração e análise com o SonarScanner
      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN_GIT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Iniciar o scanner do SonarCloud
          dotnet-sonarscanner begin \
            /k:"SofArc6Soat_framepack-worker-hackathon" \
            /o:"sofarc6soat" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.vscoveragexml.reportsPaths="tests/Worker.Tests/TestResults/**/coverage.cobertura.xml" \
            /d:sonar.inclusions="**/*.cs" \
            /d:sonar.coverage.exclusions="**/Program.cs,**/Startup.cs" \
            /d:sonar.verbose=true

          # Build da solução
          dotnet build ./Framepack-Worker.sln --configuration Release

          # Execução dos testes com coleta de cobertura
          dotnet test ./Framepack-Worker.sln --configuration Release --no-build --collect:"XPlat Code Coverage"

          # Finalizando a análise no SonarCloud
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  deploy:
    runs-on: ubuntu-latest
    needs: code_analysis
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build application
      - name: Build application
        run: dotnet build src/Worker/Worker.csproj --configuration Release

      # Deploy application
      - name: Deploy application
        run: echo "Add your deploy commands here"

  smoketest:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Run smoke tests
      - name: Run smoke tests
        run: dotnet test tests/SmokeTests/SmokeTests.csproj

  publish_docker_image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: smoketest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2        
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: build-docker-image
        run: docker buildx build --push -t sofarc6soat/framepack-worker:latest -f ./src/Worker/Dockerfile ./src
